# Generated by Django 3.2.6 on 2021-08-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
