# Generated by Django 3.2.6 on 2021-09-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speed', '0002_alter_userdata_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='date',
            field=models.CharField(max_length=30, verbose_name='date'),
        ),
    ]
