# Generated by Django 3.2.6 on 2021-09-01 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('speed', '0004_alter_userdata_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedUserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_speed', models.FloatField(verbose_name='average_speed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
