# Generated by Django 3.2.6 on 2021-09-02 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speed', '0006_alter_speeduserdata_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdata',
            options={'ordering': ('updated_at',), 'verbose_name': 'user data'},
        ),
    ]
