# Generated by Django 3.2.6 on 2021-09-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speed', '0010_alter_userdata_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDate',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('weekly', models.DateTimeField()),
                ('sum_distanse', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sum_duration', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_speed', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'group_data_by_week',
                'managed': False,
            },
        ),
    ]
