# Generated by Django 3.2.6 on 2021-09-02 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speed', '0011_reportdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportdate',
            options={'verbose_name': 'report date'},
        ),
    ]
