# Generated by Django 3.2.6 on 2021-09-02 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speed', '0012_alter_reportdate_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportdate',
            options={'managed': False},
        ),
    ]
